feat: add remove edit task
wehfis/todo-vanila-js pull request #1
Opened 2024-02-26 17:11 UTC by wehfis

Configured a project, implement add remove and edit options to each created task.

2024-02-27 09:12 UTC, BeerBaron322 requested changes

2024-02-27 09:12 UTC, BeerBaron322 commented on script.js
> +  if (!title) {
handle empty spaces

2024-02-27 09:12 UTC, BeerBaron322 commented on script.js
> +    <span>${task.title}</span>
<script> inserts

2024-02-27 09:12 UTC, BeerBaron322 commented on script.js
> +  if (target.classList.contains('btn-complete')) {
instead of class use data-set

2024-02-28 09:06 UTC, wehfis commented on script.js
> +  if (!tasksData) return;
check length

2024-02-28 09:07 UTC, wehfis commented on script.js
> +const getTasks = (key) => {
change func name

2024-02-28 09:11 UTC, wehfis commented on script.js
> +  const taskTitleElement = document.createElement('input');
change to span, when edit to input and back

2024-02-29 09:37 UTC, BeerBaron322 requested changes

2024-02-29 09:37 UTC, BeerBaron322 commented on script.js
> +  if (tasksData.length > 0) tasksData.forEach((task) => renderNewTask(task));
if () {
 ...code
}

make like this everywhere

2024-02-29 09:37 UTC, BeerBaron322 commented on script.js
> +  taskListElement.classList.remove('hidden');
unify this

2024-02-29 09:37 UTC, BeerBaron322 commented on script.js
> +  tasks = tasks.map((task) => {
add for each instead of map

2024-02-29 09:37 UTC, BeerBaron322 commented on script.js
> +filterButtons.addEventListener('click', (event) => {
refactor to single function

2024-02-29 09:37 UTC, BeerBaron322 commented on script.js
> +'use strict';
separate code blocks by enters

2024-02-29 09:39 UTC, BeerBaron322 commented
issue with editing. Shouldn't save if sting is empty (better to delete)

2024-03-01 09:19 UTC, BeerBaron322 commented on script.js
> +      if (!task.completed) renderNewTask(task);
function from new line

2024-03-01 09:20 UTC, BeerBaron322 commented on script.js
> +    button.classList.remove('active');
check comments here filterButtons.addEventListener('click', (event) ...

2024-03-01 09:20 UTC, BeerBaron322 commented on script.js
> +  turnFilters(true);
add condition to execute when it's needed

2024-03-01 09:23 UTC, BeerBaron322 commented on script.js
> +  editInput.addEventListener('blur', (event) => {
potential memory leak https://stackoverflow.com/questions/45467784/how-to-removeeventlistener-in-addeventlistenre

2024-03-01 09:25 UTC, BeerBaron322 commented on script.js
> +filterButtons.addEventListener('click', (event) => {
instead of checking all buttons just store active button in variable

activeFilter = target;

2024-03-05 10:08 UTC, merged